# Webinar 9 : Sprint 3: Introducción a Pandas

Este notebook está diseñado para reforzar el uso de estructuras condicionales, lógica booleana, bucles y funciones.

Exploraremos:

1. Uso de una nueva libreria
2. Tipos de carga de datos
3. Exploración de un conjunto de datos
4. Operaciones de filtraod y agrupación

Cada sección contiene ejercicios con explicación, código y desafíos adicionales para discutir en clase.

<div style="text-align: center">
    <img src="https://raw.githubusercontent.com/ljpiere/data_python_classes/main/DA_DS/images/9_3.png" width="600">
</div>

## 🐼 Introducción a Pandas

**Pandas** es una biblioteca de Python especializada en el análisis y manipulación de datos. Su nombre proviene de *"Panel Data"*, un término utilizado en econometría. Es una herramienta fundamental en ciencia de datos, análisis estadístico y procesamiento de información estructurada.

Con Pandas podemos:

- Cargar datos desde archivos como `.csv`, `.xlsx`, bases de datos, APIs, entre otros.
- Limpiar, filtrar y transformar datos de forma sencilla.
- Realizar análisis exploratorio mediante estadísticas descriptivas.
- Manipular series temporales y datos categóricos.
- Combinar, agrupar y reorganizar conjuntos de datos fácilmente.

Las dos estructuras de datos principales que ofrece Pandas son:

- **Series**: una lista unidimensional con etiquetas (índices).
- **DataFrames**: una tabla bidimensional con filas y columnas, similar a una hoja de cálculo o una tabla SQL.

A lo largo de esta clase aprenderemos a usar Pandas para explorar, limpiar y analizar datos reales de forma práctica.

Un par de apuntes antes de iniciar:
- Debemos de cargar la libreria en cada sesión de jupyter/python que iniciemos.
- La declaración de `import` suele ir al inicio de cada script/notebook.
- Las declaraciones de `import` pueden llevar un alias, para pandas usaremos `pd`.
- Cada vez que ingresemos a Jupyter, tendremos que volver a ejecutar las celdas para cargar la libreria y nuestros datasets. Ayudate con las opciones de ejecución en la pestaña de `Run`.

In [1]:
import pandas as pd

## 1. Carga de datos

### Ejercicio 1.1

Podemos personalizar la carga de nuestro archivo dependiendo de su naturaleza o configuraciones.

**Revisemos la documentación de las funciones de Pandas!
[pandas.read_csv](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html)**

In [2]:
# Podemos cargar el archivo especificando otros parámetros
# df = pd.read_csv("/datasets/sports.csv", sep=";", header=None, names=columnas, decimal=",")

_El `pd` nos suena familiar..._

### Ejercicio 1.2

En este ejercicio, importamos y cargamos el conjunto de datos necesario para el análisis, asegurándonos de que los datos están disponibles en un DataFrame de pandas para su posterior manipulación.

Exploraremos un poco de la carrera de Taylor Swift para este ejercicio.

In [3]:
# Cargamos el archivo
df = pd.read_csv('https://raw.githubusercontent.com/ljpiere/data_python_classes/main/DA_DS/datasets/taylor_swift_songs.csv')

_En esta ocasión no se utilizaron parámetros adicionales en la función de carga, ¿Por qué crees que no los usamos?_

## 2. Validación general

El dataframe ha quedado cargado a nuestra sesión de python en la variable `df`. Es hora de explorar el dataframe.

<div style="text-align: center">
    <img src="https://raw.githubusercontent.com/ljpiere/data_python_classes/main/DA_DS/images/3_9.jpg" width="600">
</div>

### Ejercicio 2.1

Revisemos las 5 primeras filas de nuestro dataframe.

In [4]:
# Revisemoslo!
df.head()

,Title,Album,Release Year,Duration (mins),Genre,Spotify Streams (millions),Peak Billboard Position,Songwriter(s),Producer(s),Awards
0,Love Story,Fearless,2008,3.55,Country,850,4,Swift,Chapman,Grammy
1,You Belong With Me,Fearless,2008,3.52,Country,920,2,"Swift, Rose",Chapman,NaN
2,Shake It Off,1989,2014,3.39,Pop,2500,1,"Swift, Martin, Shellback","Martin, Shellback",Grammy
3,Blank Space,1989,2014,4.32,Pop,2300,1,"Swift, Martin, Shellback","Martin, Shellback",NaN
4,All Too Well,Red,2012,5.29,Pop,600,1,Swift,Swift,Grammy

### Ejercicio 2.2

Cada columna se le podría definir como un atributo de una tabla de datos. Cada columna de pandas se puede extraer como una "serie" (Más info: sprint 7). Por ahora podemos definir cada columna con un tipo de dato diferente.

In [5]:
# Un vistazo mas especifico
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Title                       49 non-null     object
 1   Album                       49 non-null     object
 2   Release Year                49 non-null     int64
 3   Duration (mins)             49 non-null     float64
 4   Genre                       49 non-null     object
 5   Spotify Streams (millions)  49 non-null     int64
 6   Peak Billboard Position     49 non-null     int64
 7   Songwriter(s)               49 non-null     object
 8   Producer(s)                 49 non-null     object
 9   Awards                      6 non-null      object
dtypes: float64(1), int64(3), object(6)
memory usage: 4.0+ KB

_Info nos entrega varios detalles sobre nuestro dataframe, aparte del numero de columnas y su tipo de dato, ¿Qué otra información relevante observas?_

### Ejercicio 2.3

El método `head` tiene su némesis. Exploremos el método `tail`.

In [6]:
# Ultimas 5 filas
df.tail()

,Title,Album,Release Year,Duration (mins),Genre,Spotify Streams (millions),Peak Billboard Position,Songwriter(s),Producer(s),Awards
44,Ours,Speak Now,2010,4.01,Country,430,10,"Swift, Rose",Chapman,NaN
45,The Story of Us,Speak Now,2010,4.05,Country,450,12,"Swift, Rose",Chapman,NaN
46,Long Live,The Hunger Games,2012,4.02,Alternative,500,18,"Swift, T-Bone Burnett",Chapman,Grammy
47,Safe & Sound,The Hunger Games,2012,3.39,Alternative,470,19,"Swift, T-Bone Burnett",T-Bone Burnett,NaN
48,Eyes Open,Red,2012,3.53,Pop,700,1,"Swift, Martin, Shellback",T-Bone Burnett,NaN

## 3. Analisis exploratorio de los datos

### 3.1 Uso de `.loc[]` en Pandas

El método `.loc[]` permite **seleccionar y asignar** datos en un DataFrame utilizando **etiquetas** (índices y nombres de columna), en lugar de posiciones numéricas.

#### Sintaxis general
```python
df.loc[filtro_de_filas, selección_de_columnas]
```
Parámetros
- filtro_de_filas
    - Etiqueta única: una sola etiqueta de índice (df.loc[5]).
    - Lista de etiquetas: varias etiquetas (df.loc[[1, 3, 5]]).
    - Condición booleana: mascarilla que devuelve True/False por fila (df.loc[df["edad"] > 30]).
selección_de_columnas (opcional)
    - Etiqueta única: un nombre de columna (df.loc[:, "nombre"]).
    - Lista de etiquetas: varias columnas (df.loc[:, ["nombre", "edad"]]).
    - Rango de etiquetas: mediante slicing (df.loc[:, "col1":"col4"]).
    - Si se omite, se seleccionan todas las columnas (df.loc[filtro_de_filas]).

Ejemplos de uso

```python
# 1. Filtrar por condición y ver todas las columnas:
df.loc[df["ventas"] > 1000]

# 2. Filtrar filas y ver solo ciertas columnas:
df.loc[df["categoria"] == "Electrónica", ["producto", "precio"]]

# 3. Selección por etiquetas de fila y columna:
df.loc["fila_10", "columna_A"]

# 4. Asignación de valores a un subconjunto:
df.loc[df["puntuacion"] < 50, "estado"] = "revisar"
```

**Tip:** .loc respeta los nombres de índices y columnas. Para selección basada en posiciones, utiliza .iloc[].

In [7]:
# Seleccionar la fila con índice 5 (sexta fila)
df.loc[5]

Title                                 Willow
Album                               Evermore
Release Year                            2020
Duration (mins)                         3.34
Genre                            Alternative
Spotify Streams (millions)               500
Peak Billboard Position                    1
Songwriter(s)                 Swift, Dessner
Producer(s)                          Dessner
Awards                                   NaN
Name: 5, dtype: object

In [8]:
# Seleccionar las filas con índices 2, 5 y 10
df.loc[[2, 5, 10]]

,Title,Album,Release Year,Duration (mins),Genre,Spotify Streams (millions),Peak Billboard Position,Songwriter(s),Producer(s),Awards
2,Shake It Off,1989,2014,3.39,Pop,2500,1,"Swift, Martin, Shellback","Martin, Shellback",Grammy
5,Willow,Evermore,2020,3.34,Alternative,500,1,"Swift, Dessner",Dessner,NaN
10,Style,1989,2014,3.51,Pop,900,6,Swift,"Martin, Shellback",NaN

In [9]:
# Seleccionar solo la columna 'Title'
df.loc[0:5, 'Title']

0            Love Story
1    You Belong With Me
2          Shake It Off
3           Blank Space
4          All Too Well
5                Willow
Name: Title, dtype: object

In [10]:
# Seleccionar las filas 0 a 4 y las columnas 'Title' y 'Album'
df.loc[0:10, ['Title', 'Album']]

                 Title      Album
0           Love Story   Fearless
1   You Belong With Me   Fearless
2         Shake It Off       1989
3          Blank Space       1989
4         All Too Well        Red
5               Willow   Evermore
6            Anti-Hero  Midnights
7           The Archer      Lover
8       Wildest Dreams       1989
9             Cardigan   Folklore
10               Style       1989

In [11]:
# Una forma distinta de escribirlo
index_res = df.loc[5, 'Title': 'Album']
print(index_res)

Title      Willow
Album    Evermore
Name: 5, dtype: object

### 3.2 Uso de `.iloc[]` en Pandas

```python
df.iloc[fila_inicio:fila_fin, columna_inicio:columna_fin]
```
- Qué hace: Selecciona filas y/o columnas por posiciones enteras (integer-location), ignorando las etiquetas del índice.
- Sintaxis básica:
    - df.iloc[5] → quinta fila (0-based) en todas las columnas.
    - df.iloc[2:8] → filas de la 3 a la 8 (excluye la 8).
    - df.iloc[:, 1] → segunda columna en todas las filas.
    - df.iloc[3:6, 0:2] → filas 4-6 y columnas 1-2.

**Uso típico:** Cuando se necesita seleccionar por posiciones numéricas o hacer slicing posicional en lugar de por etiquetas.

In [12]:
df.iloc[5]

Title                                 Willow
Album                               Evermore
Release Year                            2020
Duration (mins)                         3.34
Genre                            Alternative
Spotify Streams (millions)               500
Peak Billboard Position                    1
Songwriter(s)                 Swift, Dessner
Producer(s)                          Dessner
Awards                                   NaN
Name: 5, dtype: object

### 3.3 Slicing por posición en Pandas

```python
df[9:20]
Qué hace: Selecciona las filas cuya posición (integer-location) va de la 9 (incluida) hasta la 20 (excluida).
```

Equivalente a:

```
df.iloc[9:20]
```
**Uso típico:** Extraer un bloque continuo de filas para inspección o procesamiento.

In [15]:
# de la 9 a la 20, incluidas
index_res = df[9:20]
print(index_res)

                       Title       Album  Release Year  Duration (mins)  \
9                   Cardigan    Folklore          2020             4.00
10                     Style        1989          2014             3.51
11                  Delicate  Reputation          2017             3.55
12  Look What You Made Me Do  Reputation          2017             3.31
13              Cruel Summer       Lover          2019             2.58
14                 Enchanted   Speak Now          2010             5.52
15                       Red         Red          2012             3.43
16                        22         Red          2012             3.52
17          Out of the Woods        1989          2014             3.56
18                      Mean   Speak Now          2010             3.57
19                     The 1    Folklore          2020             3.31

         Genre  Spotify Streams (millions)  Peak Billboard Position  \
9   Indie Folk                         700                        6
10         Pop                         900                        6
11  Electropop                         750                        7
12  Electropop                         780                        1
13         Pop                         820                        5
14     Country                         450                        5
15     Country                         510                        6
16         Pop                         520                        6
17   Synth-pop                         900                        6
18     Country                         400                       11
19  Indie Folk                         700                        4

               Songwriter(s)        Producer(s)  Awards
9             Swift, Dessner            Dessner  Grammy
10                     Swift  Martin, Shellback     NaN
11           Swift, Antonoff           Antonoff     NaN
12  Swift, Martin, Shellback  Martin, Shellback     NaN
13           Swift, Antonoff           Antonoff     NaN
14                     Swift              Swift     NaN
15               Swift, Rose            Chapman     NaN
16               Swift, Rose            Chapman     NaN
17           Swift, Antonoff           Antonoff     NaN
18                     Swift              Swift  Grammy
19            Swift, Dessner            Dessner     NaN

### 3.4 Operaciones de filtrado en Pandas

```python
df[df['Album'] == '1989']
```
- Selecciona todas las filas donde la columna **Album** es igual a `'1989'`.

```python
df[(df['Spotify Streams (millions)'] >= 900) & (df['Spotify Streams (millions)'] <= 1000)]
```
- Selecciona filas donde **Spotify Streams (millions)** está entre 900 y 1000 (inclusive).  
- Utiliza el operador **&** para combinar condiciones booleanas y paréntesis para agrupar cada condición.

> Estas técnicas se conocen como **indexación booleana** o **filtrado condicional**, y devuelven un DataFrame con solo las filas que cumplen los criterios especificados.

In [16]:
# Filtrar canciones que pertenecen al álbum '1989'
df[df['Album'] == '1989']

,Title,Album,Release Year,Duration (mins),Genre,Spotify Streams (millions),Peak Billboard Position,Songwriter(s),Producer(s),Awards
2,Shake It Off,1989,2014,3.39,Pop,2500,1,"Swift, Martin, Shellback","Martin, Shellback",Grammy
3,Blank Space,1989,2014,4.32,Pop,2300,1,"Swift, Martin, Shellback","Martin, Shellback",NaN
8,Wildest Dreams,1989,2014,3.40,Dream pop,850,3,"Swift, Martin, Shellback","Martin, Shellback",NaN
10,Style,1989,2014,3.51,Pop,900,6,Swift,"Martin, Shellback",NaN
17,Out of the Woods,1989,2014,3.56,Synth-pop,900,6,"Swift, Antonoff",Antonoff,NaN
20,New Romantics,1989,2014,3.51,Electropop,850,11,"Swift, Antonoff",Antonoff,NaN
30,This Love,1989,2014,4.10,Pop,750,18,"Swift, Antonoff",Antonoff,NaN
37,Lover,1989,2014,4.29,Pop,700,9,"Swift, Antonoff",Antonoff,NaN

In [17]:
# Filtrar canciones con reproducciones entre 500 y 1000 millones
df[(df['Spotify Streams (millions)'] >= 900) & (df['Spotify Streams (millions)'] <= 1000)]

,Title,Album,Release Year,Duration (mins),Genre,Spotify Streams (millions),Peak Billboard Position,Songwriter(s),Producer(s),Awards
1,You Belong With Me,Fearless,2008,3.52,Country,920,2,"Swift, Rose",Chapman,NaN
10,Style,1989,2014,3.51,Pop,900,6,Swift,"Martin, Shellback",NaN
17,Out of the Woods,1989,2014,3.56,Synth-pop,900,6,"Swift, Antonoff",Antonoff,NaN

## 3.5 Funciones de agregación

### 3.5.1 Conteo

In [18]:
# Contar cuántos valores no nulos hay en cada columna
df.count()

Title                         49
Album                         49
Release Year                  49
Duration (mins)               49
Genre                         49
Spotify Streams (millions)    49
Peak Billboard Position       49
Songwriter(s)                 49
Producer(s)                   49
Awards                         6
dtype: int64

In [19]:
df['Title'].count()

49

### 3.5.2 Promedio, mediana y moda

In [20]:
# Promedio de la duración de las canciones
df['Duration (mins)'].mean()

3.8026530612244893

In [14]:
# Moda de la duración de las canciones
df['Duration (mins)'].mode()

0    3.31
1    3.55
2    3.57
3    4.01
4    4.20
Name: Duration (mins), dtype: float64

In [15]:
# Media de la duración de las canciones
df['Duration (mins)'].median()

3.57

### 3.5.3 Suma

In [21]:
# Duración total de todas las canciones en minutos
df['Duration (mins)'].sum()

186.32999999999998

## 3.6 Podemos filtrar y agregar sobre una columna

In [22]:
# Promedio de duración de canciones lanzadas después de 2015
df[df['Release Year'] > 2015]['Duration (mins)'].mean()

3.7805882352941174

**Descripción:** Ejecutamos una operación de análisis exploratorio sobre el DataFrame.

In [23]:
# Promedio de 'Duration (mins)' y 'Spotify Streams (millions)'
df[['Duration (mins)', 'Spotify Streams (millions)']].mean()

Duration (mins)                 3.802653
Spotify Streams (millions)    637.959184
dtype: float64

### 3.7 Operaciones de agrupamiento con `groupby` en Pandas

- **Qué hace**: Agrupa filas del DataFrame según valores de una o varias columnas, devolviendo un objeto `GroupBy` sobre el que se pueden aplicar funciones de agregación, transformación o filtrado.

- **Sintaxis básica**:
```python
df.groupby('columna')
df.groupby(['col1', 'col2'])
```

- **Métodos comunes**:
  - `agg()` o `aggregate()`: aplica funciones agregadas.
  - `mean()`, `sum()`, `count()`, `min()`, `max()`.
  - `size()`: devuelve el tamaño de cada grupo.
  - `get_group(nombre_grupo)`: obtiene el subconjunto correspondiente a un grupo específico.

- **Ejemplos**:
```python
# 1. Suma de ventas por categoría
df.groupby('categoria')['ventas'].sum()

# 2. Estadísticas descriptivas por región
df.groupby('region').describe()

# 3. Número de registros por usuario
df.groupby('usuario').size()

# 4. Aplicar múltiples agregaciones a ventas
df.groupby('categoria')['ventas'].agg(['sum', 'mean', 'max'])
```

In [25]:
df.groupby('Release Year')['Title'].count()

Release Year
2006     3
2008     3
2010    10
2012     8
2014     8
2017     2
2019     5
2020     9
2022     1
Name: Title, dtype: int64

## Final: Actividad colaborativa (Breakroom) 💬

Usando los conceptos aprendidos en este notebook sobre **estructuras condicionales aplicadas a DataFrames con Pandas**, resuelvan el siguiente desafío en grupo:

### 🧩 Desafío:

Supongan que tienen un DataFrame `ventas` con los siguientes datos:

```python
import pandas as pd

ventas = pd.DataFrame({
    "producto": ["Laptop", "Camisa", "Cereal", "Silla", "Audífonos", "Zapatos"],
    "precio": [1500, 30, 5, 400, 80, 100],
    "categoria": ["tecnología", "ropa", "alimentos", "hogar", "tecnología", "ropa"]
})
```

### 🛠️ Tarea:

1. Crear una nueva columna `"etiqueta"` aplicando la siguiente lógica:
   - `"Gama alta"` si el precio es mayor a 100 y la categoría es `"tecnología"`
   - `"Lujo"` si el precio es mayor a 300 y **no** es tecnología
   - `"Económico"` si el precio es menor a 20
   - `"Estándar"` para los demás casos

2. Mostrar solo los productos que fueron clasificados como `"Lujo"` o `"Gama alta"`.

### 💬 Discute en grupo:
- ¿Qué pasa si hay valores nulos o tipos inconsistentes?
- ¿Cómo podrías ordenar el DataFrame por etiqueta?
- ¿Qué otra lógica de negocio se podría aplicar a este tipo de tabla?

**Descripción:** Ejecutamos una operación de análisis exploratorio sobre el DataFrame.