# Webinar 9 : Sprint 3: Práctica de Python Intermedio

Este notebook está diseñado para reforzar el uso de estructuras condicionales, lógica booleana, bucles y funciones.

Exploraremos:

1. Evaluaciones compuestas
2. Condiciones anidadas
3. Lógica aplicada en flujos tipo formulario
4. Simulación de escenarios reales en Python

Cada sección contiene ejercicios con explicación, código y desafíos adicionales para discutir en clase.

## 0. Una nueva librería

In [4]:
import pandas as pd

## 1. Condicionales anidadas

### Ejercicio s.1
Explica qué hace el siguiente código y ejecútalo para comprobar su comportamiento.

In [5]:
# Podemos cargar el archivo especificando otros parámetros
# df = pd.read_csv("/datasets/sports.csv", sep=";", header=None, names=columnas, decimal=",")

### Ejercicio s.2
Explica qué hace el siguiente código y ejecútalo para comprobar su comportamiento.

In [6]:
# Cargamos el archivo
df = pd.read_csv('datasets/taylor_swift_songs.csv')

### Ejercicio s.3
Explica qué hace el siguiente código y ejecútalo para comprobar su comportamiento.

In [7]:
# Revisemoslo!
df.head(7)

,Title,Album,Release Year,Duration (mins),Genre,Spotify Streams (millions),Peak Billboard Position,Songwriter(s),Producer(s),Awards
0,Love Story,Fearless,2008,3.55,Country,850,4,Swift,Chapman,Grammy
1,You Belong With Me,Fearless,2008,3.52,Country,920,2,"Swift, Rose",Chapman,NaN
2,Shake It Off,1989,2014,3.39,Pop,2500,1,"Swift, Martin, Shellback","Martin, Shellback",Grammy
3,Blank Space,1989,2014,4.32,Pop,2300,1,"Swift, Martin, Shellback","Martin, Shellback",NaN
4,All Too Well,Red,2012,5.29,Pop,600,1,Swift,Swift,Grammy
5,Willow,Evermore,2020,3.34,Alternative,500,1,"Swift, Dessner",Dessner,NaN
6,Anti-Hero,Midnights,2022,3.20,Pop,800,1,"Swift, Antonoff",Antonoff,NaN

### Ejercicio s.4
Explica qué hace el siguiente código y ejecútalo para comprobar su comportamiento.

In [8]:
# Un vistazo mas especifico
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Title                       49 non-null     object
 1   Album                       49 non-null     object
 2   Release Year                49 non-null     int64
 3   Duration (mins)             49 non-null     float64
 4   Genre                       49 non-null     object
 5   Spotify Streams (millions)  49 non-null     int64
 6   Peak Billboard Position     49 non-null     int64
 7   Songwriter(s)               49 non-null     object
 8   Producer(s)                 49 non-null     object
 9   Awards                      6 non-null      object
dtypes: float64(1), int64(3), object(6)
memory usage: 4.0+ KB

### Ejercicio s.5
Explica qué hace el siguiente código y ejecútalo para comprobar su comportamiento.

In [9]:
# Ultimas 5 filas
df.tail()

,Title,Album,Release Year,Duration (mins),Genre,Spotify Streams (millions),Peak Billboard Position,Songwriter(s),Producer(s),Awards
44,Ours,Speak Now,2010,4.01,Country,430,10,"Swift, Rose",Chapman,NaN
45,The Story of Us,Speak Now,2010,4.05,Country,450,12,"Swift, Rose",Chapman,NaN
46,Long Live,The Hunger Games,2012,4.02,Alternative,500,18,"Swift, T-Bone Burnett",Chapman,Grammy
47,Safe & Sound,The Hunger Games,2012,3.39,Alternative,470,19,"Swift, T-Bone Burnett",T-Bone Burnett,NaN
48,Eyes Open,Red,2012,3.53,Pop,700,1,"Swift, Martin, Shellback",T-Bone Burnett,NaN

## 2. Evaluación booleana compuesta

### Ejercicio a.1
Explica qué hace el siguiente código y ejecútalo para comprobar su comportamiento.

In [10]:
# Seleccionar la fila con índice 5 (sexta fila)
df.loc[5]

Title                                 Willow
Album                               Evermore
Release Year                            2020
Duration (mins)                         3.34
Genre                            Alternative
Spotify Streams (millions)               500
Peak Billboard Position                    1
Songwriter(s)                 Swift, Dessner
Producer(s)                          Dessner
Awards                                   NaN
Name: 5, dtype: object

### Ejercicio a.2
Explica qué hace el siguiente código y ejecútalo para comprobar su comportamiento.

In [11]:
# Seleccionar las filas con índices 2, 5 y 10
df.loc[[2, 5, 10]]

,Title,Album,Release Year,Duration (mins),Genre,Spotify Streams (millions),Peak Billboard Position,Songwriter(s),Producer(s),Awards
2,Shake It Off,1989,2014,3.39,Pop,2500,1,"Swift, Martin, Shellback","Martin, Shellback",Grammy
5,Willow,Evermore,2020,3.34,Alternative,500,1,"Swift, Dessner",Dessner,NaN
10,Style,1989,2014,3.51,Pop,900,6,Swift,"Martin, Shellback",NaN

### Ejercicio a.3
Explica qué hace el siguiente código y ejecútalo para comprobar su comportamiento.

In [12]:
# Seleccionar solo la columna 'Title'
df.loc[0:5, 'Title']

0            Love Story
1    You Belong With Me
2          Shake It Off
3           Blank Space
4          All Too Well
5                Willow
Name: Title, dtype: object

### Ejercicio a.4
Explica qué hace el siguiente código y ejecútalo para comprobar su comportamiento.

In [13]:
# Seleccionar las filas 0 a 4 y las columnas 'Title' y 'Album'
df.loc[0:10, ['Title', 'Album']]

                 Title      Album
0           Love Story   Fearless
1   You Belong With Me   Fearless
2         Shake It Off       1989
3          Blank Space       1989
4         All Too Well        Red
5               Willow   Evermore
6            Anti-Hero  Midnights
7           The Archer      Lover
8       Wildest Dreams       1989
9             Cardigan   Folklore
10               Style       1989

### Ejercicio a.5
Explica qué hace el siguiente código y ejecútalo para comprobar su comportamiento.

In [14]:
# Una forma distinta de escribirlo
index_res = df.loc[5, 'Title': 'Album']
print(index_res)

Title      Willow
Album    Evermore
Name: 5, dtype: object

## 3. Simulación de decisiones

### Ejercicio s.1
Explica qué hace el siguiente código y ejecútalo para comprobar su comportamiento.

In [15]:
# de la 9 a la 20, incluidas
index_res = df[9:20]
print(index_res)

                       Title       Album  Release Year  Duration (mins)  \
9                   Cardigan    Folklore          2020             4.00
10                     Style        1989          2014             3.51
11                  Delicate  Reputation          2017             3.55
12  Look What You Made Me Do  Reputation          2017             3.31
13              Cruel Summer       Lover          2019             2.58
14                 Enchanted   Speak Now          2010             5.52
15                       Red         Red          2012             3.43
16                        22         Red          2012             3.52
17          Out of the Woods        1989          2014             3.56
18                      Mean   Speak Now          2010             3.57
19                     The 1    Folklore          2020             3.31

         Genre  Spotify Streams (millions)  Peak Billboard Position  \
9   Indie Folk                         700                        6
10         Pop                         900                        6
11  Electropop                         750                        7
12  Electropop                         780                        1
13         Pop                         820                        5
14     Country                         450                        5
15     Country                         510                        6
16         Pop                         520                        6
17   Synth-pop                         900                        6
18     Country                         400                       11
19  Indie Folk                         700                        4

               Songwriter(s)        Producer(s)  Awards
9             Swift, Dessner            Dessner  Grammy
10                     Swift  Martin, Shellback     NaN
11           Swift, Antonoff           Antonoff     NaN
12  Swift, Martin, Shellback  Martin, Shellback     NaN
13           Swift, Antonoff           Antonoff     NaN
14                     Swift              Swift     NaN
15               Swift, Rose            Chapman     NaN
16               Swift, Rose            Chapman     NaN
17           Swift, Antonoff           Antonoff     NaN
18                     Swift              Swift  Grammy
19            Swift, Dessner            Dessner     NaN

### Ejercicio s.2
Explica qué hace el siguiente código y ejecútalo para comprobar su comportamiento.

In [16]:
# Filtrar canciones que pertenecen al álbum '1989'
df[df['Album'] == '1989']

,Title,Album,Release Year,Duration (mins),Genre,Spotify Streams (millions),Peak Billboard Position,Songwriter(s),Producer(s),Awards
2,Shake It Off,1989,2014,3.39,Pop,2500,1,"Swift, Martin, Shellback","Martin, Shellback",Grammy
3,Blank Space,1989,2014,4.32,Pop,2300,1,"Swift, Martin, Shellback","Martin, Shellback",NaN
8,Wildest Dreams,1989,2014,3.40,Dream pop,850,3,"Swift, Martin, Shellback","Martin, Shellback",NaN
10,Style,1989,2014,3.51,Pop,900,6,Swift,"Martin, Shellback",NaN
17,Out of the Woods,1989,2014,3.56,Synth-pop,900,6,"Swift, Antonoff",Antonoff,NaN
20,New Romantics,1989,2014,3.51,Electropop,850,11,"Swift, Antonoff",Antonoff,NaN
30,This Love,1989,2014,4.10,Pop,750,18,"Swift, Antonoff",Antonoff,NaN
37,Lover,1989,2014,4.29,Pop,700,9,"Swift, Antonoff",Antonoff,NaN

### Ejercicio s.3
Explica qué hace el siguiente código y ejecútalo para comprobar su comportamiento.

In [17]:
# Filtrar canciones con reproducciones entre 500 y 1000 millones
df[(df['Spotify Streams (millions)'] >= 900) & (df['Spotify Streams (millions)'] <= 1000)]

,Title,Album,Release Year,Duration (mins),Genre,Spotify Streams (millions),Peak Billboard Position,Songwriter(s),Producer(s),Awards
1,You Belong With Me,Fearless,2008,3.52,Country,920,2,"Swift, Rose",Chapman,NaN
10,Style,1989,2014,3.51,Pop,900,6,Swift,"Martin, Shellback",NaN
17,Out of the Woods,1989,2014,3.56,Synth-pop,900,6,"Swift, Antonoff",Antonoff,NaN

### Ejercicio s.4
Explica qué hace el siguiente código y ejecútalo para comprobar su comportamiento.

In [18]:
# Contar cuántos valores no nulos hay en cada columna
df.count()

Title                         49
Album                         49
Release Year                  49
Duration (mins)               49
Genre                         49
Spotify Streams (millions)    49
Peak Billboard Position       49
Songwriter(s)                 49
Producer(s)                   49
Awards                         6
dtype: int64

### Ejercicio s.5
Explica qué hace el siguiente código y ejecútalo para comprobar su comportamiento.

In [19]:
df['Title'].count()

49

## 4. Funciones con condicionales

### Ejercicio s.1
Explica qué hace el siguiente código y ejecútalo para comprobar su comportamiento.

In [20]:
# Promedio de la duración de las canciones
df['Duration (mins)'].mean()

3.8026530612244893

### Ejercicio s.2
Explica qué hace el siguiente código y ejecútalo para comprobar su comportamiento.

In [21]:
# Duración total de todas las canciones en minutos
df['Duration (mins)'].sum()

186.32999999999998

### Ejercicio s.3
Explica qué hace el siguiente código y ejecútalo para comprobar su comportamiento.

In [22]:
# Promedio de duración de canciones lanzadas después de 2015
df[df['Release Year'] > 2015]['Duration (mins)'].mean()

3.7805882352941174

### Ejercicio s.4
Explica qué hace el siguiente código y ejecútalo para comprobar su comportamiento.

In [23]:
# Promedio de 'Duration (mins)' y 'Spotify Streams (millions)'
df[['Duration (mins)', 'Spotify Streams (millions)']].mean()

Duration (mins)                 3.802653
Spotify Streams (millions)    637.959184
dtype: float64

### Ejercicio s.5
Explica qué hace el siguiente código y ejecútalo para comprobar su comportamiento.

In [24]:
df.head(2)

,Title,Album,Release Year,Duration (mins),Genre,Spotify Streams (millions),Peak Billboard Position,Songwriter(s),Producer(s),Awards
0,Love Story,Fearless,2008,3.55,Country,850,4,Swift,Chapman,Grammy
1,You Belong With Me,Fearless,2008,3.52,Country,920,2,"Swift, Rose",Chapman,NaN

### Ejercicio s.6
Explica qué hace el siguiente código y ejecútalo para comprobar su comportamiento.

In [25]:
df.groupby('Release Year')['Title'].count()

Release Year
2006     3
2008     3
2010    10
2012     8
2014     8
2017     2
2019     5
2020     9
2022     1
Name: Title, dtype: int64

## 5. Actividad colaborativa (Breakroom) 💬

Usando los conceptos aprendidos en este notebook sobre **estructuras condicionales aplicadas a DataFrames con Pandas**, resuelvan el siguiente desafío en grupo:

### 🧩 Desafío:

Supongan que tienen un DataFrame `ventas` con los siguientes datos:

```python
import pandas as pd

ventas = pd.DataFrame({
    "producto": ["Laptop", "Camisa", "Cereal", "Silla", "Audífonos", "Zapatos"],
    "precio": [1500, 30, 5, 400, 80, 100],
    "categoria": ["tecnología", "ropa", "alimentos", "hogar", "tecnología", "ropa"]
})
```

### 🛠️ Tarea:

1. Crear una nueva columna `"etiqueta"` aplicando la siguiente lógica:
   - `"Gama alta"` si el precio es mayor a 100 y la categoría es `"tecnología"`
   - `"Lujo"` si el precio es mayor a 300 y **no** es tecnología
   - `"Económico"` si el precio es menor a 20
   - `"Estándar"` para los demás casos

2. Mostrar solo los productos que fueron clasificados como `"Lujo"` o `"Gama alta"`.

### 💬 Discute en grupo:
- ¿Qué pasa si hay valores nulos o tipos inconsistentes?
- ¿Cómo podrías ordenar el DataFrame por etiqueta?
- ¿Qué otra lógica de negocio se podría aplicar a este tipo de tabla?