# Clasificación de Planes Megaline — Modelos Separados (Versión corregida)

## Objetivos  
- Generar datos sintéticos.  
- Preparar los conjuntos de datos.  
- Entrenar y evaluar **Logistic Regression**, **Random Forest** y **Gradient Boosting** en secciones separadas.  
- Seleccionar correctamente el mejor modelo y realizar la prueba de cordura.

## 1. Generación de datos sintéticos

In [1]:
import pandas as pd, numpy as np
rng = np.random.default_rng(42)
n_samples = 5000
df = pd.DataFrame({
    'calls': rng.integers(0, 250, n_samples),
    'minutes': np.abs(rng.normal(400, 200, n_samples)),
    'messages': rng.integers(0, 300, n_samples),
    'mb_used': np.abs(rng.normal(5000, 3000, n_samples))
})
df['is_ultra'] = ((df['minutes'] > 600) | (df['mb_used'] > 8000)).astype(int)
df.head()

   calls     minutes  messages      mb_used  is_ultra
0     22  324.779162       281  3352.502425         0
1    193  308.383640       266  1026.940902         0
2    163  553.793174       187  5750.746927         0
3    109  563.820834       173  8228.525075         1
4    108  292.982569       108  6083.141406         0

### Resumen

In [2]:
df.info()

df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   calls     5000 non-null   int64
 1   minutes   5000 non-null   float64
 2   messages  5000 non-null   int64
 3   mb_used   5000 non-null   float64
 4   is_ultra  5000 non-null   int32
dtypes: float64(2), int32(1), int64(2)
memory usage: 175.9 KB

             calls      minutes     messages       mb_used     is_ultra
count  5000.000000  5000.000000  5000.000000   5000.000000  5000.000000
mean    124.159400   406.207672   148.194600   5093.477847     0.297000
std      72.357415   193.271170    87.047436   2809.808836     0.456982
min       0.000000     0.562748     0.000000      0.015807     0.000000
25%      61.000000   267.423864    72.000000   3005.210021     0.000000
50%     123.000000   399.650960   148.500000   4938.257547     0.000000
75%     187.000000   537.377728   223.000000   6998.482472     1.000000
max     249.000000  1090.809280   299.000000  17453.724191     1.000000

## 2. Preparación y división

In [31]:
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, classification_report

In [5]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

X = df.drop(columns=['is_ultra'])
y = df['is_ultra']
# scaler = StandardScaler()
#X_scaled = scaler.fit_transform(X)

X_temp, X_test, y_temp, y_test = train_test_split(X, y, test_size=0.2,
                                                  random_state=42, stratify=y)
X_train, X_test, y_train, y_test = train_test_split(X_temp, y_temp, test_size=0.25,
                                                      random_state=42, stratify=y_temp)
print(f'Train: {X_train.shape}, Valid: {X_valid.shape}, Test: {X_test.shape}')

Train: (3000, 4), Valid: (1000, 4), Test: (1000, 4)

## 3. Lineal Regression

In [4]:
from sklearn.linear_model import LinearRegression

reg = LinearRegression()
reg.fit(X_train, y_train)

LinearRegression()

In [7]:
y_predict = reg.predict(X_test)

In [12]:
accuracy_score(y_test, best_log.predict(X_test))

0.856

## 4. Decission Tree

In [13]:
from sklearn.tree import DecisionTreeClassifier

In [23]:
clf = DecisionTreeClassifier(max_depth=1, random_state=0)

In [24]:
clf.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=1, random_state=0)

In [25]:
accuracy_score(y_test, clf.predict(X_test))

0.854

In [29]:
profundidades = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 20, 30, 50]

In [30]:
for i in profundidades:
    clf = DecisionTreeClassifier(max_depth=i, random_state=0)
    clf.fit(X_train, y_train)
    prec = accuracy_score(y_test, clf.predict(X_test))
    print("Profundidad: ", i, ". Accuaracy: ", prec)

Profundidad:  1 . Accuaracy:  0.854
Profundidad:  2 . Accuaracy:  0.996
Profundidad:  3 . Accuaracy:  0.998
Profundidad:  4 . Accuaracy:  0.998
Profundidad:  5 . Accuaracy:  0.998
Profundidad:  6 . Accuaracy:  0.998
Profundidad:  7 . Accuaracy:  0.998
Profundidad:  8 . Accuaracy:  0.998
Profundidad:  9 . Accuaracy:  0.998
Profundidad:  10 . Accuaracy:  0.998
Profundidad:  20 . Accuaracy:  0.998
Profundidad:  30 . Accuaracy:  0.998
Profundidad:  50 . Accuaracy:  0.998

## 3. Logistic Regression

### 3.1 Ajuste

In [32]:
from sklearn.linear_model import LogisticRegression

In [33]:
log_reg = LogisticRegression(max_iter=2000)
log_reg.fit(X_train, y_train)

LogisticRegression(max_iter=2000)

In [34]:
accuracy_score(y_test, log_reg.predict(X_test))

0.853

In [43]:
profundidades = [100, 300, 500, 1000, 5000]

for i in profundidades:
    clf = LogisticRegression(max_iter=i)
    clf.fit(X_train, y_train)
    prec = accuracy_score(y_test, clf.predict(X_test))
    print("Profundidad: ", i, ". Accuaracy: ", prec)

Profundidad:  100 . Accuaracy:  0.853
Profundidad:  300 . Accuaracy:  0.853
Profundidad:  500 . Accuaracy:  0.853
Profundidad:  1000 . Accuaracy:  0.853
Profundidad:  5000 . Accuaracy:  0.853

## 4. Random Forest

### 4.1 Ajuste

In [48]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=1000, max_depth=10, random_state=42)
rf.fit(X_train, y_train)

RandomForestClassifier(max_depth=10, n_estimators=1000, random_state=42)

In [50]:
accuracy_score(y_test, rf.predict(X_test))

1.0

In [51]:
profundidades = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 20, 30, 50]
numero_arboles = [10, 40, 50, 100, 500, 700]

for i in profundidades:
    for j in numero_arboles:
        clf = RandomForestClassifier(n_estimators=j, max_depth=i, random_state=42)
        clf.fit(X_train, y_train)
        prec = accuracy_score(y_test, clf.predict(X_test))
        print("Estimador: ", j, "Profundidad: ", i, ". Accuaracy: ", prec)

Estimador:  10 Profundidad:  1 . Accuaracy:  0.997
Estimador:  40 Profundidad:  1 . Accuaracy:  0.857
Estimador:  50 Profundidad:  1 . Accuaracy:  1.0
Estimador:  100 Profundidad:  1 . Accuaracy:  0.873
Estimador:  500 Profundidad:  1 . Accuaracy:  0.873
Estimador:  700 Profundidad:  1 . Accuaracy:  0.997
Estimador:  10 Profundidad:  2 . Accuaracy:  1.0
Estimador:  40 Profundidad:  2 . Accuaracy:  0.999
Estimador:  50 Profundidad:  2 . Accuaracy:  0.999
Estimador:  100 Profundidad:  2 . Accuaracy:  1.0
Estimador:  500 Profundidad:  2 . Accuaracy:  1.0
Estimador:  700 Profundidad:  2 . Accuaracy:  1.0
Estimador:  10 Profundidad:  3 . Accuaracy:  1.0
Estimador:  40 Profundidad:  3 . Accuaracy:  1.0
Estimador:  50 Profundidad:  3 . Accuaracy:  1.0
Estimador:  100 Profundidad:  3 . Accuaracy:  1.0
Estimador:  500 Profundidad:  3 . Accuaracy:  1.0
Estimador:  700 Profundidad:  3 . Accuaracy:  1.0
Estimador:  10 Profundidad:  4 . Accuaracy:  0.999
Estimador:  40 Profundidad:  4 . Accuaracy:  1.0
Estimador:  50 Profundidad:  4 . Accuaracy:  1.0
Estimador:  100 Profundidad:  4 . Accuaracy:  1.0
Estimador:  500 Profundidad:  4 . Accuaracy:  1.0
Estimador:  700 Profundidad:  4 . Accuaracy:  1.0
Estimador:  10 Profundidad:  5 . Accuaracy:  0.999
Estimador:  40 Profundidad:  5 . Accuaracy:  0.999
Estimador:  50 Profundidad:  5 . Accuaracy:  0.999
Estimador:  100 Profundidad:  5 . Accuaracy:  1.0
Estimador:  500 Profundidad:  5 . Accuaracy:  1.0
Estimador:  700 Profundidad:  5 . Accuaracy:  1.0
Estimador:  10 Profundidad:  6 . Accuaracy:  0.999
Estimador:  40 Profundidad:  6 . Accuaracy:  1.0
Estimador:  50 Profundidad:  6 . Accuaracy:  0.999
Estimador:  100 Profundidad:  6 . Accuaracy:  1.0
Estimador:  500 Profundidad:  6 . Accuaracy:  1.0
Estimador:  700 Profundidad:  6 . Accuaracy:  1.0
Estimador:  10 Profundidad:  7 . Accuaracy:  0.999
Estimador:  40 Profundidad:  7 . Accuaracy:  0.999
Estimador:  50 Profundidad:  7 . Accuaracy:  0.999
Estimador:  100 Profundidad:  7 . Accuaracy:  1.0
Estimador:  500 Profundidad:  7 . Accuaracy:  1.0
Estimador:  700 Profundidad:  7 . Accuaracy:  1.0
Estimador:  10 Profundidad:  8 . Accuaracy:  0.999
Estimador:  40 Profundidad:  8 . Accuaracy:  0.999
Estimador:  50 Profundidad:  8 . Accuaracy:  0.999
Estimador:  100 Profundidad:  8 . Accuaracy:  1.0
Estimador:  500 Profundidad:  8 . Accuaracy:  1.0
Estimador:  700 Profundidad:  8 . Accuaracy:  1.0
Estimador:  10 Profundidad:  9 . Accuaracy:  0.999
Estimador:  40 Profundidad:  9 . Accuaracy:  1.0
Estimador:  50 Profundidad:  9 . Accuaracy:  0.999
Estimador:  100 Profundidad:  9 . Accuaracy:  1.0
Estimador:  500 Profundidad:  9 . Accuaracy:  1.0
Estimador:  700 Profundidad:  9 . Accuaracy:  1.0
Estimador:  10 Profundidad:  10 . Accuaracy:  0.999
Estimador:  40 Profundidad:  10 . Accuaracy:  1.0
Estimador:  50 Profundidad:  10 . Accuaracy:  0.999
Estimador:  100 Profundidad:  10 . Accuaracy:  1.0
Estimador:  500 Profundidad:  10 . Accuaracy:  1.0
Estimador:  700 Profundidad:  10 . Accuaracy:  1.0
Estimador:  10 Profundidad:  20 . Accuaracy:  0.999
Estimador:  40 Profundidad:  20 . Accuaracy:  1.0
Estimador:  50 Profundidad:  20 . Accuaracy:  0.999
Estimador:  100 Profundidad:  20 . Accuaracy:  1.0
Estimador:  500 Profundidad:  20 . Accuaracy:  1.0
Estimador:  700 Profundidad:  20 . Accuaracy:  1.0
Estimador:  10 Profundidad:  30 . Accuaracy:  0.999
Estimador:  40 Profundidad:  30 . Accuaracy:  1.0
Estimador:  50 Profundidad:  30 . Accuaracy:  0.999
Estimador:  100 Profundidad:  30 . Accuaracy:  1.0
Estimador:  500 Profundidad:  30 . Accuaracy:  1.0
Estimador:  700 Profundidad:  30 . Accuaracy:  1.0
Estimador:  10 Profundidad:  50 . Accuaracy:  0.999
Estimador:  40 Profundidad:  50 . Accuaracy:  1.0
Estimador:  50 Profundidad:  50 . Accuaracy:  0.999
Estimador:  100 Profundidad:  50 . Accuaracy:  1.0
Estimador:  500 Profundidad:  50 . Accuaracy:  1.0
Estimador:  700 Profundidad:  50 . Accuaracy:  1.0

## 6. Comparación de resultados

In [10]:
results = pd.DataFrame({
    'Modelo':['Logistic Regression','Random Forest','Gradient Boosting'],
    'Validación':[val_acc_log,val_acc_rf,val_acc_gb],
    'Test':[test_acc_log,test_acc_rf,test_acc_gb]
}).sort_values('Test', ascending=False).reset_index(drop=True)
results

                Modelo  Validación   Test
0        Random Forest       1.000  1.000
1    Gradient Boosting       0.999  1.000
2  Logistic Regression       0.858  0.845

## 7. Prueba de cordura del mejor modelo

In [11]:
# Seleccionar el modelo con mejor score en test
best_model_name = results.iloc[0]['Modelo']
best_models_dict = {
    'Logistic Regression': best_log,
    'Random Forest': best_rf,
    # 'Gradient Boosting': best_gb # Esto lo podemos saltar
}
best_model = best_models_dict[best_model_name]

perm = rng.permutation(len(X_test))
sanity_acc = accuracy_score(y_test, best_model.predict(X_test[perm]))
print(f'Mejor modelo: {best_model_name}  |  Accuracy permutado: {sanity_acc:.3f}')

Mejor modelo: Random Forest  |  Accuracy permutado: 0.580

## 8. Conclusiones  
- Se corrigió la selección del modelo ganador usando el nombre completo.  
- La prueba de cordura valida que el modelo aprende patrones reales.